# Generated by Django 5.1.8 on 2025-04-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('payments', 'Payments'), ('house', 'House'), ('transportation', 'Transportation'), ('clothing', 'Clothing'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('others', 'Others')], default='others', max_length=50, verbose_name='Expense category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='accounts.account', verbose_name='Account from expense')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expense',
            },
        ),
    ]
